//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sinav.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hakkimizda
    {
        public int Personelid { get; set; }
        public string Ad { get; set; }
        public string Aciklama { get; set; }
        public string Görev { get; set; }
        public string Resim { get; set; }
    }
}
